[package]
name = "pesde-registry"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/pesde-pkg/index"
publish = false

[lints]
workspace = true

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.7.0"
actix-governor = "0.8.0"
dotenvy = "0.15.7"
thiserror = "2.0.11"
tantivy = "0.22.0"
semver = "1.0.25"
jiff = { version = "0.1.29", features = ["serde"] }
futures = "0.3.31"
tokio = "1.43.0"
tokio-util = "0.7.13"
tempfile = "3.16.0"
fs-err = { version = "3.1.0", features = ["tokio"] }
async-stream = "0.3.6"

git2 = "0.20.0"
gix = { version = "0.70.0", default-features = false, features = [
    "blocking-http-transport-reqwest-rust-tls",
    "credentials",
] }

serde = "1.0.217"
serde_json = "1.0.138"
serde_yaml = "0.9.34"
toml = "0.8.20"
convert_case = "0.7.1"
sha2 = "0.10.8"

rusty-s3 = "0.7.0"
reqwest = { version = "0.12.12", default-features = false, features = ["json", "rustls-tls"] }
constant_time_eq = "0.3.1"

tokio-tar = "0.3.1"
async-compression = { version = "0.4.18", features = ["tokio", "gzip"] }

tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-actix-web = "0.7.15"

sentry = { version = "0.36.0", default-features = false, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls", "tracing"] }
sentry-actix = "0.36.0"

pesde = { path = "..", default-features = false, features = ["wally-compat"] }
