app = 'pesde-registry'
primary_region = 'waw'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
ADDRESS = '0.0.0.0'
PORT = '8080'
COMMITTER_GIT_NAME = 'pesde index updater'
COMMITTER_GIT_EMAIL = 'pesde@daimond113.com'
INDEX_REPO_URL = 'https://github.com/pesde-pkg/index'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
